# Generated by Django 3.2.12 on 2025-02-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_no', models.IntegerField()),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.TextField()),
                ('clas', models.IntegerField()),
                ('course', models.TextField()),
            ],
        ),
    ]
