# Generated by Django 3.2.12 on 2025-02-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='ad_no',
            new_name='admno',
        ),
    ]
