# Generated by Django 3.2.12 on 2025-02-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_admno_students_admission_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='admission_no',
            new_name='adm_no',
        ),
    ]
