# Generated by Django 3.2.12 on 2025-02-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
