# Generated by Django 3.2.12 on 2025-02-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Pwd',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Uname',
            new_name='uname',
        ),
    ]
