# Generated by Django 5.1.6 on 2025-03-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_remove_user_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='')),
                ('des', models.TextField()),
            ],
        ),
    ]
